// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQGBfwlkpXULg8tqaoPCEKpZWFlZCrhig',
    appId: '1:52636022306:web:09ed828ce073d313e87c7b',
    messagingSenderId: '52636022306',
    projectId: 'db-hotels1',
    authDomain: 'db-hotels1.firebaseapp.com',
    storageBucket: 'db-hotels1.firebasestorage.app',
    measurementId: 'G-V70FP25FGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4qibPwcT1gHkFWdZl1dKa-sgjdtMN2DA',
    appId: '1:52636022306:android:2a27f8a70229eb24e87c7b',
    messagingSenderId: '52636022306',
    projectId: 'db-hotels1',
    storageBucket: 'db-hotels1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8BdotBazxKolLFv9HSIQj3XJW6eXaD-k',
    appId: '1:52636022306:ios:ae3cf46eb7a220b1e87c7b',
    messagingSenderId: '52636022306',
    projectId: 'db-hotels1',
    storageBucket: 'db-hotels1.firebasestorage.app',
    iosBundleId: 'com.example.hotels1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8BdotBazxKolLFv9HSIQj3XJW6eXaD-k',
    appId: '1:52636022306:ios:ae3cf46eb7a220b1e87c7b',
    messagingSenderId: '52636022306',
    projectId: 'db-hotels1',
    storageBucket: 'db-hotels1.firebasestorage.app',
    iosBundleId: 'com.example.hotels1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQGBfwlkpXULg8tqaoPCEKpZWFlZCrhig',
    appId: '1:52636022306:web:16f53d283689d48ae87c7b',
    messagingSenderId: '52636022306',
    projectId: 'db-hotels1',
    authDomain: 'db-hotels1.firebaseapp.com',
    storageBucket: 'db-hotels1.firebasestorage.app',
    measurementId: 'G-FS0BGK58ZK',
  );
}
